//ASPECTOS DE PERSONALIDAD

SELF_ESTEEM
CAUTION
COGNITION
DISCIPLINE
CONFORMISM
FLEXIBILITY

//SESGOS COGNITIVOS
OVER_CONFIDENCE = "overConfidence";
REPRESENTATIVENESS
SELF_ATTRIBUTION
ANCHORING_EFFECT
MENTAL_ACCOUNTING
CONFIRMATION_BIAS
ENDOWMENT_EFFECT

//SESGOS EMOCIONALES
DISPOSITION_EFFECT
LOSS_AVERSION = "lossAversion";
HERD_BEHAVIOR
INSTANT_GRATIFICATION
REGRET_AVERSION
STATUS_QUO
PROCASTINATION = "procastination";
SELF_CONTROL = "selfControl";
